### ISSUE TITLE
Currently not functioning at all-- shipyard corners not projecting lasers and not forming shipyards

### ISSUE THREAD

**Issue by LegendOfCatBro** [StarCoreSE/InvalidsMiscMods#55]
I was in a multiplayer game with my friend, and we constructed a shipyard. The corner blocks in the terminal had no options related to being a shipyard, and did not project any lasers when placed and did not highlight any grids inside of them. 

I created a new empty singleplayer world with no mods except for the shipyards mod, and the issue persisted, so i don't think its a mod conflict?

 I'm busy playing with my friend right now but I can send log files later today if y'all can't reproduce the issue

**Comment by InvalidArgument3** [comment]
Recommend not using the mod and instead using something like 
https://steamcommunity.com/sharedfiles/filedetails/?id=2111073562 or 
https://steamcommunity.com/sharedfiles/filedetails/?id=219757726.
 The scripts were temp disabled for an event since they were lagging out clients and the mod is in need of a complete overhaul over the next few weeks

**Comment by InvalidArgument3** [comment]
re enabled it, gonna work on another branch for fixes
